### ISSUE TITLE
Question about darkmode contribution

### ISSUE THREAD

**Issue by andylib93** [feliixx/mongoplayground#108]
Hi @feliixx,
I like your playground and was wondering if a contribution regarding [darkmode](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) would be appreciated? I'd go with plain CSS variables in a `:root {}` block and set the variables according to the users system preferences. Here is an [example](https://webkit.org/blog/8840/dark-mode-support-in-webkit/), so nothing fancy really, but a nice user feature in my opinion. Let me know, what you think.

**Comment by feliixx** [comment]
Hi @andylib93, 

Yes, that would be great ! I've been thinking about it for some time, but never took the time to implement it 
Please let me know if you need help

**Comment by andylib93** [comment]
Great, the only think I could think of is the hex color values you'd prefer for darkmode. Do you have something in mind or should I just try something and you correct the PR with your preferences?

**Comment by feliixx** [comment]
I really enjoy the `dark dimmed` theme in github, can you use it for inspiration ?

**Comment by andylib93** [comment]
I'll give it a try 👍🏻

**Comment by feliixx** [comment]
darkmode is now live in the playground, thanks again for your help !

**Comment by andylib93** [comment]
This is amazing 🤩 I'm glad I could help 🙏🏻

**Comment by rickhg12hs** [comment]
@feliixx @andylib93 Is there a way to turn this on/off in `mongoplayground.net`?

**Comment by andylib93** [comment]
Well besides changing your system settings, unfortunately no. It would require a button that detects the user's settings. With JavaScript this could be accomplished with the `localStorage` API (not really elegant in my opinion). But given the fact that there are no stored users, it would have to be solved with clientside code.
