### ISSUE TITLE
Many links in `docs.html` don't work

### ISSUE THREAD

**Issue by rickhg12hs** [feliixx/mongoplayground#112]
I noticed many links in the docs didn't work while learning `mgodatagen` configurations, etc.  You should also know that I am no HTML expert, so my comments about the details may be off the mark.

You can see the `href`'s beginning at https://github.com/feliixx/mongoplayground/blob/dev/internal/web/static/docs.html#L94
```html
        <li><a href="#string">string</a></li>
        <li><a href="#int">int</a></li>
        <li><a href="#long">long</a></li>
        <li><a href="#double">double</a></li>
        <li><a href="#decimal">decimal</a></li>
        <li><a href="#autoincrement">autoincrement</a></li>
        <li><a href="#boolean">boolean</a></li>
        <li><a href="#objectid">objectId</a></li>
        <li><a href="#binary">binary</a></li>
        <li><a href="#date">date</a></li>
        <li><a href="#uuid">UUID</a></li>
        <li><a href="#position">position</a></li>
        <li><a href="#faker">faker</a></li>
    </ul>
    <p>List of composite <code>&lt;generator&gt;</code> types:</p>
    <ul>
        <li><a href="#array">array</a></li>
        <li><a href="#object">object</a></li>
        <li><a href="#constant">constant</a></li>
        <li><a href="#ref">reference</a></li>
        <li><a href="#fromarray">fromArray</a></li>
        <li><a href="#stringFromParts">stringFromParts</a></li>
        <li><a href="#countAggregator">countAggregator</a></li>
        <li><a href="#valueAggregator">valueAggregator</a></li>
        <li><a href="#boundAggregator">boundAggregator</a></li>
    </ul>
    <h3><a id="user-content-string" class="anchor" aria-hidden="true" href="#string"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>String</h3>
```
Notice the last line above, `id="user-content-string"`. This seems to parallel other `id` assignments that appear earlier in the document.  However, also notice that `href="#string"` in the list above.  Shouldn't it be `href="#user-content-string"`? ... and all the other `href` assignments should be changed too?  Also notice the last line has `href="#string"` - this should also probably be changed, or removed?

**Comment by feliixx** [comment]
yes, there is something wrong here. We should just get rid of all the `user-content` in order to simply have this: 

```
<li><a href="#string">string</a></li>
...
<h3><a id="string" class="anchor" aria-hidden="true">...</a>String</h3>
```

**Comment by rickhg12hs** [comment]
Or maybe have it more subject related, like `<li><a href="#mgodatagen-string">string</a></li>`.

**Comment by feliixx** [comment]
yes, that would be even better

**Comment by rickhg12hs** [comment]
I'd try to submit a PR, but it would be a bit like a monkey creating a work of Shakespeare - my HTML knowledge is pretty low.  And I really don't know how I would test my changes.

**Comment by feliixx** [comment]
that would be great ! The best way to test your changes is to run the playground locally, either with `docker-compose` if you're familiar with it, or directly from the command line, but you'll need to install mongodb on your computer 
If it's not practical for you, just submit the PR and I'll test it for you
