### ISSUE TITLE
Enhancement Request:  View Selectable Pipeline Stage Output

### ISSUE THREAD

**Issue by rickhg12hs** [feliixx/mongoplayground#114]
It would enhance query/pipeline development if the output of each stage was viewable, even after adding further stages.  It is currently possible to "comment out" or cut stages from a pipeline to view a particular stage's output, but it's inconvenient , time consuming, and prone to error.

One possible implementation might be to have an additional tabbed pane in the Result pane for stage output.  Some way to select the stage in the Query pane or the new tab in the Result pane would be necessary -  there are many possibilities.  It would be especially important to show the output as if the following stages do not exist since a typical use case would be to view the stage's output while still having a partial or faulty stage below it under development. 

If the "zeroth stage" i.e., the input collection, could be selected, then #113 would be redundant since the collection could be viewed in the stage tab of the Result pane with this enhancement.

**Comment by feliixx** [comment]
This is something I've been thinking about for a long time, an I have an idea on how to do it. I'll try to implement it in the next few days

**Comment by feliixx** [comment]
started working on this here: https://github.com/feliixx/mongoplayground/pull/116

it works but I need to improve the UI, feel free to test it and let me know if you have any ideas

**Comment by rickhg12hs** [comment]
It'll be awesome when it's done.  Unfortunately I don't have a way to test it right now.  When it goes live, I'll pound on it.  :-)

**Comment by feliixx** [comment]
@rickhg12hs this is now live in the playground, please let me know if you have any suggestions on how to improve it

**Comment by rickhg12hs** [comment]
@feliixx  Will do!

**Comment by rickhg12hs** [comment]
@feliixx Staged Output is awesome!

It would also be nice if a "pre-pipeline" stage could be selected so that an entire collection, or the output of `mgodatagen`, could be viewed.

**Comment by rickhg12hs** [comment]
I was looking at a Stack Exchange question/answer that provided a [`mongoplayground.net` link](https://mongoplayground.net/p/hoz24xP_BNV) where there are 2 `"$match"` stages and 2 `"$unwind"` stages.  Selecting either stage of the same operator showed the output from the last stage only.

**Comment by feliixx** [comment]
thanks for the report, this should be fixed now
