### ISSUE TITLE
Colon in the value is breaking aggregation queries and also the output order of fields changed too

### ISSUE THREAD

**Issue by saagar2000** [feliixx/mongoplayground#13]
example here https://mongoplayground.net/p/zULrmihM03z

More details 

https://stackoverflow.com/questions/60996149/push-if-object-doesnt-already-exist

`"profile_picture": "https://productionstemulistorage.blob.core.windows.net/stemuli/profile-picture-6e609f3b-44cb-44c0-888a-1b6767e3072d"`

It works as expected when I run the query locally.

Expected result :

```
[
  {
    "_id": null,
    "students": [
      {
        "userId": "5dd27452592f600900235945",
        "name": "student  zero",
        "profile_picture": "https://productionstemulistorage.blob.core.windows.net/stemuli/profile-picture-6e609f3b-44cb-44c0-888a-1b6767e3072d"
      }
    ]
  }
]
```

Also not sure why the fields order has been changed in the result.

**Comment by feliixx** [comment]
Hi @saagar2000, thanks for the report 

I fixed the wrap behavior of the result editor so it doesn't wrap the content if there is no error. For the field order, it looks like the new mongodb driver decided to sort document fields alphabetically. I agree that it's weird, I'll see if I can restore the old behavior somehow

**Comment by saagar2000** [comment]
Thanks. It works but looks like similar variant with different input field order is broken. https://mongoplayground.net/p/D5l0HK6tVSZ
