### ISSUE TITLE
Mistakenly added sensitive data, how to delete playground

### ISSUE THREAD

**Issue by tahafarooqui** [feliixx/mongoplayground#140]
How to delete mongoplayground as I have added sensitive information while testing queries .

**Comment by feliixx** [comment]
Hi @tahafarooqui, 

It's impossible to delete a playground from the website 
If you send me the playground ID by email, I'll delete it directly from the database ( my email is on my github profile )

**Comment by tahafarooqui** [comment]
@feliixx Please check your email.

**Comment by feliixx** [comment]
@tahafarooqui I just deleted both playground, it should be fine now
