### ISSUE TITLE
Enhancement Request:  Accept Canonical MongoDB Extended JSON (v2) `"$binary"` in BSON Configuration

### ISSUE THREAD

**Issue by rickhg12hs** [feliixx/mongoplayground#151]
It would be convenient , and more closely align `mongoplayground.net` to MongoDB, if the [Canonical MongoDB Extended JSON (v2) `"$binary"`](https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/#mongodb-bsontype-Binary) was accepted in `mongoplayground.net`'s BSON configuration.

Currently, with a BSON configuration of: [[mongoplayground.net link](https://mongoplayground.net/p/tRColaNoHNm)]
```json
[
  {
    "_id": {
      "$oid": "6359dd697a7dcbd7a0bae8d9"
    },
    "payload": {
      "$binary": {
        "base64": "SSB3aXNoIHRoaXMgd291bGQgd29yayEK",
        "subType": "00"
      }
    }
  }
]
```
... the _Result_ shows error:
```
error in configuration:
  json: cannot unmarshal object into Go value of type []uint8
```
`BinData()` is a workaround for this, but it is inconvenient to transform given Canonical MongoDB Extended JSON (v2) `"$binary"` to this form.

**Comment by feliixx** [comment]
I think there is an error in your query, the `base64` field should not be here !

The correct syntax is [mongoplayground.net/p/-19dT3QVe6N](https://mongoplayground.net/p/GD6ua7PINch)

```
[
  {
    "payload": {
      "$binary": "SSB3aXNoIHRoaXMgd291bGQgd29yayEK",
      "subType": "00"
    }
  }
]
```

**Comment by rickhg12hs** [comment]
Hi @feliixx, I see your [mongoplayground.net example](https://mongoplayground.net/p/GD6ua7PINch) works, but I don't see that syntax in the [Canonical MongoDB Extended JSON (v2) docs](https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/#mongodb-bsontype-Binary).

In addition, MongoDB Compass won't accept that syntax.

<details><summary>MongoDB Compass "insert doc" screenshot</summary>

![Screenshot from 2022-10-27 21-30-49](https://user-images.githubusercontent.com/6000188/198381813-e84f4dc0-9c1a-4262-8e9b-1db18d604270.png)
</details>

And Compass shows the MongoDB doc's canocial format:

<details><summary>MongoDB Compass "collection view" screenshot</summary>

![Screenshot from 2022-10-27 21-35-32](https://user-images.githubusercontent.com/6000188/198382351-e20b7c34-0025-4a5e-bb03-772a5ddea6df.png)
</details>

When I export the entire collection from Compass, the JSON file is:

<details><summary>`cat compassBinaryExport.json`</summary>

```json
$ cat compassBinaryExport.json
[{
  "_id": {
    "$oid": "6359dd697a7dcbd7a0bae8d7"
  },
  "payload": {
    "$binary": {
      "base64": "ZDE6YWQyOmlkMjA6gXf9FgF8UygM5L82L9oENAkOXvs2OnRhcmdldDIwOgve6moxv7muYKlCE7G+z8DlIiuLZTE6cTk6ZmluZF9ub2RlMTp0MjpNgTE6djQ6TFQAEDE6eTE6cWU=",
      "subType": "00"
    }
  }
},{
  "_id": {
    "$oid": "6359dd697a7dcbd7a0bae8d8"
  },
  "payload": {
    "$binary": {
      "base64": "",
      "subType": "00"
    }
  }
},{
  "_id": {
    "$oid": "6359dd697a7dcbd7a0bae8d9"
  },
  "payload": {
    "$binary": {
      "base64": "SSB3aXNoIHRoaXMgd291bGQgd29yayEK",
      "subType": "00"
    }
  }
}]
```
</details>

Using `mongoexport` shows the MongoDB doc's canonical format:

<details><summary>`mongoexport ...` output</summary>

```json
$ mongoexport -d binaryData -c test --type json --jsonArray --pretty --jsonFormat=canonical mongodb+srv://redacted0:redacted1@stackexchange0.w426d.mongodb.net/
2022-10-27T21:51:00.149+0200	connected to: mongodb+srv://[**REDACTED**]@stackexchange0.w426d.mongodb.net/
[{
	"_id": {
		"$oid": "6359dd697a7dcbd7a0bae8d7"
	},
	"payload": {
		"$binary": {
			"base64": "ZDE6YWQyOmlkMjA6gXf9FgF8UygM5L82L9oENAkOXvs2OnRhcmdldDIwOgve6moxv7muYKlCE7G+z8DlIiuLZTE6cTk6ZmluZF9ub2RlMTp0MjpNgTE6djQ6TFQAEDE6eTE6cWU=",
			"subType": "00"
		}
	}
},
{
	"_id": {
		"$oid": "6359dd697a7dcbd7a0bae8d8"
	},
	"payload": {
		"$binary": {
			"base64": "",
			"subType": "00"
		}
	}
},
{
	"_id": {
		"$oid": "6359dd697a7dcbd7a0bae8d9"
	},
	"payload": {
		"$binary": {
			"base64": "SSB3aXNoIHRoaXMgd291bGQgd29yayEK",
			"subType": "00"
		}
	}
}]

2022-10-27T21:51:00.268+0200	exported 3 records
```
</details>

Using `mongoexport ... --jsonFormat=relaxed ...` shows the same output.

**Comment by feliixx** [comment]
Oh sorry, I read your issue too quickly! Indeed what I proposed is MongoDB Extended JSON v1. 
I'll update the parser to accept this v2 syntax.

**Comment by rickhg12hs** [comment]
Super!

**Comment by feliixx** [comment]
Hi @rickhg12hs, I've updated the playground to accept MongoDB Extended JSONv2, so this [mongoplayground.net/p/tRColaNoHNm](https://mongoplayground.net/p/tRColaNoHNm) works fine now! 

Thanks again for the report
