### ISSUE TITLE
how long do you keep a "share"d playground on mongoplayground.net?

### ISSUE THREAD

**Issue by yilmazdurmaz** [feliixx/mongoplayground#156]
Hey there, It is a great tool you created here.

I met this for the first time today on MongoDb Forums, where one participant of the topic has used it to test the problem. I loved how it made the trial/error easy.

I now wonder how long you keep those playgrounds around . Since there is no mention of this on the main site, I thought it would be acceptable to ask here.

**Comment by feliixx** [comment]
Hi @yilmazdurmaz, 

Shared playgrounds are kept forever, they are never deleted!
