### ISSUE TITLE
The position of the toolbar is not correct in Edge Browser.

### ISSUE THREAD

**Issue by mrdulin** [feliixx/mongoplayground#165]
The position of the toolbar should be in the upper left corner, but it is at the bottom, and the dropdown menu exceeds the viewport and cannot be scrolled, see below:

![image](https://github.com/feliixx/mongoplayground/assets/17866683/99895a6f-341f-4cd1-956f-d0c88c6c1768)

Edge: 113.0.1774.57
OS: Mac 10.15.7

**Comment by feliixx** [comment]
Hi @mrdulin, thank you for reporting this. I could not reproduce the issue with Edge 113, what version of Edge are you using?
