### ISSUE TITLE
possible to create docker image?

### ISSUE THREAD

**Issue by bwgjoseph** [feliixx/mongoplayground#21]
Hi,

Wondering if this can be package and pushed as a docker image? Or any way to self-host this?

Thanks!

**Comment by feliixx** [comment]
Hi, 

I was planning to create a docker image, I might do this in the following weeks. However, you can self-host a playground on any server you want with this steps: 

- [download go](https://golang.org/dl/)
- clone this repo 
- go in the repo and run `go build`
- start the server with `./mgodatagen`
