### ISSUE TITLE
Please support explain clause

### ISSUE THREAD

**Issue by SergeAx** [feliixx/mongoplayground#28]
First of all, thank you for a great tool! Glad to see it under active development.

I think that it really needs to support "explain", to answer a frequent question "willl this request use my indexes?" and solving other performance-related problems.

I see it as an easy update to .js and can make a pull request, if you like the idea.

**Comment by feliixx** [comment]
Hi @SergeAx , 

indeed it would be very useful, however indexes are currently not supported in the playground right now ( see #25 ) 
I'd like to add support for index before doing this, but I don't know how to do it yet

If you're interested in working on this, you're welcome !

**Comment by SergeAx** [comment]
#31

**Comment by feliixx** [comment]
I'll try to implement this soon, now that indexes are supported! 

This requires some change in the front-end. It' might not be trivial, but feel free to give it a try if you want !

**Comment by feliixx** [comment]
@SergeAx it should work fine now: https://mongoplayground.net/p/A-tyGh5-XU7
