### ISSUE TITLE
Error in configuration: server selection error: server selection timeout, current topology:

### ISSUE THREAD

**Issue by turivishal** [feliixx/mongoplayground#37]
Seems like server is down, it show below error in result:

```
error in configuration:
  server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: localhost:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp 127.0.0.1:27017: connect: connection refused }, ] }
```

**Comment by feliixx** [comment]
Hi @turivishal, thanks for the report

the mongod server crashed for some reason, I've restarted it and it should work fine

Do you know what was the query causing the server to crash ? 

JIRA ticket: [SERVER-53929](https://jira.mongodb.org/browse/SERVER-53929)

**Comment by turivishal** [comment]
@feliixx  It will be little easy to track from last log from `mongod.log` file.
