### ISSUE TITLE
Running {$range : [0, 259200000, 1]} server not responds

### ISSUE THREAD

**Issue by Valijon** [feliixx/mongoplayground#4]
Reproducing issue:

**Input**

    {
       startDate: ISODate("2020-01-07T00:00:00.000Z"),
       endDate: ISODate("2020-01-10T00:00:00.000Z")
    }

**Query**

    db.collection.aggregate([
       {
         $addFields: {
           range: {
             $range:[0, {
                 $subtract: [
                   "$endDate",
                   "$startDate"
                 ]
               }, 1]
           }
         }
       }
    ])

Accidential query execution...

**Comment by feliixx** [comment]
Hi @Valijon, thanks for the report ! This is actually a problem from MongoDB itself. This aggregation query would generate a multi-gigabytes array containing 259 200 000 integers and if the server has not enough ram/disk space, it may make the mongod server crash 

Sadly the playground is running on a small VM that has not enough resources for such queries :/
