### ISSUE TITLE
Aggregate does not seem to work

### ISSUE THREAD

**Issue by alexkosau** [feliixx/mongoplayground#5]
Thanks for the great program!

Currently, the db.collection.aggregate() seems to be broken.
I run [this example:](https://mongoplayground.net/p/_SE7eKctyam)
and the error text is: 
```
invalid query: 
  must match db.coll.find(...) or db.coll.aggregate(...)
```

**Comment by feliixx** [comment]
Hi @alexkosau, thanks for the report ! I couldn't reproduce the error ( neither on chrome nor firefox ). What browser are you using ?

**Comment by alexkosau** [comment]
Thank you for looking at this!
I use Chrome, but even I can't reproduce the issue any more.
I think you can close it now, and I'll keep an eye on it.
