### ISSUE TITLE
query failed: Unrecognized pipeline stage name: '$regexFind'

### ISSUE THREAD

**Issue by mpenicaud** [feliixx/mongoplayground#6]
The new $regexFind, $regexFindAll and $regexMatch are not recognized in aggregagtion queries

**Comment by feliixx** [comment]
Hi @mpenicaud, these operators should work fine in mongoplayground, see for exemple: 

[**$regexFind**: mongoplayground.net/p/5YPDDVQOrUk](https://mongoplayground.net/p/5YPDDVQOrUk)
[**$regexMatch**: mongoplayground.net/p/_eICukwL2yA](https://mongoplayground.net/p/_eICukwL2yA)

This won't work if you use `/pattern/` for the regex, but will work with `"pattern"`. This is the same limitation as for `$regex`, see https://github.com/feliixx/mongoplayground#shell-regex for details

**Comment by mpenicaud** [comment]
ok, my fault, i tried to use it as stage instead of operator... Must have been tired. Sry, i close issue.
