### ISSUE TITLE
Expected 'a' instead of 'u'

### ISSUE THREAD

**Issue by dheemanth-bhat** [feliixx/mongoplayground#62]
Getting below error while using `$function` operator:
```
Invalid query:

Line 9: Expected 'a' instead of 'u'
```
Playground links:
Link where it can be reproduced in simple way:
https://mongoplayground.net/p/cr4VaSp2bJL

Link where actually problem occurred.
https://mongoplayground.net/p/IDToAhOArq6

**Comment by feliixx** [comment]
Hi @DheemanthBhat, thanks for the report

currently the only way to make a js function work is to quote the body like this: 

```
db.collection.aggregate([
  {
    $addFields: {
      "key": {
        $function: {
          body: "function(key){ return key+1 }",
          args: [
            "$key"
          ],
          lang: "js"
        }
      }
    }
  }
])
```
https://mongoplayground.net/p/W1UldtXDEdH

closing in favor of #22
