### ISSUE TITLE
Having "run" next to "Mongo Playground" (aka "Throw Away All Your Work") is a bit tedious

### ISSUE THREAD

**Issue by nitwhiz** [feliixx/mongoplayground#68]
I love the playground but.. I just lost a good amount of work. Because I missclicked on "Mongo Playground" in the top left. Why is that a feature? The Go Playground doesn't do this.

**Comment by feliixx** [comment]
Hi @nitwhiz 

you're right, clicking on the title shouldn't redirect. It's a bug introduced by a recent refactoring, I've reverted it. 
thanks for the report !
